baseURL = "https://christiancasey.github.io/"
relativeURLs = false
sourceRelativeLinksEval = false
languageCode = "en-us"
title = "Gardens of the Roman Empire"
theme = "mainroad"

publishDir = "docs"

buildDrafts = false
enableEmoji = true
enableInlineShortcodes = true

[menu]

	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = -110

	[[menu.main]]
		identifier = "province"
		name = "Provinces"
		url = "/province/"
		weight = -100

	[[menu.main]]
		identifier = "garden"
		name = "Gardens"
		url = "/garden/"
		weight = -90


[Params.sidebar]
	home = "right" # Configure layout for home page
	list = "left"  # Configure layout for list pages
	single = false # Configure layout for single pages
	# Enable widgets in given order
	widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
	# alternatively "ddg-search" can be used, to search via DuckDuckGo
	# widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
	recent_num = 5 # Set the number of articles in the "Recent articles" widget
	tags_counter = false # Enable counter for each tag in "Tags" widget