baseURL = "https://christiancasey.github.io"
relativeURLs = false
sourceRelativeLinksEval = true
languageCode = "en-us"
title = "Gardens of the Roman Empire"
theme = "mainroad"
publishDir = "docs"

[params]
  mainSections = ["about", "garden"]